name: event_marker
description: A cross-platform event tracker with calendar sync and group features.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0  # ✅ Added
  provider: ^6.1.2
  image_picker: ^1.1.0
  intl: ^0.19.0
  table_calendar: ^3.0.9
  http: ^1.2.1
  uuid: ^4.2.1
  file_picker: ^6.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

  # Optional (keep only if used)
  google_sign_in: ^6.1.6
  url_launcher: ^6.2.6
  flutter_local_notifications: ^16.3.2
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
