name: event_marker
description: A cross-platform event tracker with calendar sync and group features.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 2.24.2
  firebase_auth: 4.15.3
  firebase_storage: 11.5.3
  firebase_messaging: 14.7.10
  cloud_firestore: ^4.14.0
 # google_sign_in: 6.1.5
  http: 1.1.0


  provider: ^6.1.2
  image_picker: ^1.1.0
  intl: ^0.19.0
  table_calendar: ^3.0.9
  uuid: ^4.2.1
#  file_picker: ^5.2.5
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

  # Optional (keep only if used)
  url_launcher: ^6.2.6
  flutter_local_notifications: ^16.3.2
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  
dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master
  cloud_firestore: ^4.14.0



flutter:
  uses-material-design: true

  assets:
    - assets/
